dist: trusty
language: java
addons:
  sonarcloud:
    organization: "shryne-github"
    token:
      secure: "c951f5b986877f7cc10ba93ab691a7a11a2216fe"
jdk: openjdk11
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  # Yes, it has to be this long and inside one row...
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report sonar:sonar -Dsonar.projectKey=io.github.shryne:NrJson